### PR TITLE
Form squad screen

### PR DESCRIPTION
**Pull request by aspitz1**
## What does this PR do?
- [x] New feature (adds functionality)
- [ ] Debugging/Refactor
 
### Where should your reviewer start?
- `formSquadScreen`
### What (if any) features are you implementing?
- Adding form to create a squad
### What (if anything) did you refactor?
- mock-user data
### What issues does this PR close?
- #17 
### Is there anything that you need from your teammates?
- The "submit" button doesn't do anything, I am guessing that it will eventually be tied to an event that makes an object from the component's state to send to the API
- I think the date may need formatting before sent to the API, see [Date.UTC on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC)
### Any other comments, questions, or concerns?
- The date / time that is displayed still needs formatting for instances when there is a single digit that needs a "0" in front of it.
- I tried to comment the code well, there is a lot going on
### How Has This Been Tested?
- [x] I tested my changes in the browser
- [ ] I tested with Cypress

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new bugs
- [ ] I have added tests that prove my fix is effective or that my feature works
Screenshot_1666127433
] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tfettig22 — COMMENTED** [review]
Everything seems great except for when i pick a date and time, the green ':date at :time' is not updating to the chosen values, it seems to just display the current date/time. Otherwise I really like the styling and how the date/time pickers work. Seems like it was a very complicated component so thank you for working through it

**Comment by aspitz1** [comment]
I'll check that out @tfettig22! Thank you 👍

**Comment by aspitz1** [comment]
@tfettig22 I fixed that bug, but found another. The invite button doesn't seem to be working. I am going to fix that too.

I seemed to have broke the datepicker trying to make it work better, so I basically went back to previous working code. Thank you for catching that!!

**Comment by aspitz1** [comment]
@tfettig22 I fixed the invite button and added feedback so the user can see who they have invited. Now the whole button turns green if the user selects it. 


Screenshot_1666145187

**Review by NickLiggett — APPROVED** [review]
Nice Component! Great work, Anna! Thank you for deleting the commented code!

**Review by tfettig22 — APPROVED** [review]
Changes look great, works well! thanks Anna!

**Pull request merged**
