### PR TITLE
Consistent styling

### PR DESCRIPTION
**Pull request by tfettig22**
## What does this PR do?
- [] New feature (adds functionality)
- [x] Debugging/Refactor
 
### Where should your reviewer start?
- Updated styling across all screens
### What (if any) features are you implementing?
- Style refactor
### What (if anything) did you refactor?
- Styling
### What issues does this PR close?
- #61 
### Is there anything that you need from your teammates?
- Please let me know if anything looks weird or if you have any suggestions for changing up colors/borders/etc.  I am totally open to changing things if theres something you guys don't like.

### How Has This Been Tested?
- [x] I tested my changes in the browser

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new bugs

### CODE REVIEW

**Review by NickLiggett — APPROVED** [review]

**Review by aspitz1 — COMMENTED** [review]
I love the way the styling looks! Seems like there may be a bug though, not sure when it may have come about. The game detail modal is broken from the `HomeScreen`

**Comment by aspitz1** [comment]
Looks like somewhere along the way we've lost the `imageClickHandler ` that is on the image

**Comment by tfettig22** [comment]
I thought we decided to remove that feature, because the game data from HomeScreen doesn't include genre and console information? I think I forgot to delete that Pressable, but the clickHandler function doesn't exist anymore

actually now that I'm thinking about it I don't remember why we scrapped this one, we should be able to get genre and console data, but I think there was some issue with the Modal...🤷🏼‍♂️

**Comment by aspitz1** [comment]
Oh yeah! that's right

I'll add a comment to remove it

**Comment by aspitz1** [comment]
@tfettig22  Actually, I can't b/c it isn't part of the PR. I forgot :/

**Review by aspitz1 — APPROVED** [review]
I'm fine if this gets merged in whenever you are ready 👍

**Pull request merged**
